# Prerequisites
tap "caskroom/cask"
tap "neovim/neovim"

# Must be installed first
cask "java"

brew "awscli"
brew "cmake"
brew "ctags"
brew "direnv"
brew "elasticsearch"
brew "exercism"
brew "git"
brew "gnupg2"
brew "go"
brew "gpg-agent"
brew "kubectl"
brew "magic-wormhole"
brew "matplotlib"
brew "mongodb"
brew "neovim"
brew "node"
brew "numpy"
brew "python"
brew "python3"
brew "reattach-to-user-namespace"
brew "redis"
brew "ripgrep"
brew "sbt"
brew "scala"
brew "scipy"
brew "tmux"
brew "vim"
brew "yarn"
brew "z"
brew "zsh"

cask "1password"
cask "firefox"
cask "google-chrome"
cask "google-drive"
cask "iterm2"
cask "slack"
cask "telegram"
cask "the-unarchiver"
cask "vlc"
