# Prerequisites
tap "homebrew/dupes"
tap "caskroom/cask"

brew "cmake"
brew "elixir"
brew "exercism"
brew "vim"
brew "macvim"
brew "mongodb"
brew "python"
brew "redis"
brew "sbt"
brew "the_silver_searcher"

cask "1password"
cask "chitchat"
cask "firefox"
cask "google-chrome"
cask "google-drive"
cask "iterm2"
cask "java"
cask "skype"
cask "slack"
cask "stelegram"
cask "the-unarchiver"
cask "vlc"
